databases:
  - name: demo_imagenes
    databaseName: demo_imagenes
    user: demo_imagenes
 
services:
  - type: web
    name: demo_imagenes
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn demo_imagenes.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: demo_imagenes
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: PYTHON_VERSION
        value: 3.10.6
